include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    unnecessary_this: true
    prefer_final_fields: true
    no_leading_underscores_for_local_identifiers: false
    prefer_typing_uninitialized_variables: false
    avoid_unnecessary_containers: true
    prefer_interpolation_to_compose_strings: true
    sort_child_properties_last: true
    curly_braces_in_flow_control_structures: true
    use_build_context_synchronously: true
    library_private_types_in_public_api: false
    prefer_if_null_operators: true
    unnecessary_null_checks: true
    prefer_adjacent_string_concatenation: true
    avoid_returning_null_for_void: true
    avoid_dynamic_calls: true
    always_declare_return_types: true
    omit_local_variable_types: false
    type_init_formals: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    unnecessary_string_interpolations: true
    unnecessary_new: true
    unnecessary_overrides: true
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true